# -*- coding: utf-8 -*-
"""pizzaorder-akbankpythonbootcamp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/erdemdgl/621173cd0b7a4648909cc765bcbb449b/pizzaorder-akbankpythonbootcamp.ipynb
"""

import csv 
import datetime
import pandas as pd

with open("Orders_Database.csv", 'w') as file_csv:
    writer = csv.writer(file_csv)
    writer.writerow(["Time", "Description", "Cost", "Name", "Identity Number", "Credit Card Number","Credit Card Password"])

file = open('Menu.txt','w')
file.write('Seçebileceğiniz Pizzalar:\n1:Margherita \n2:Pepperoni \n3:Hawaiian \n4:Vegetarian \n5:Jalapeno \n\nSeçebileceğiniz Yan Ürünler:\n1:Ispanak \n2:Köri Sosu \n3:Keçi Peyniri \n4:Köz Patlıcan \n5:Mısır \n\nTeşekkür ederiz!')
file.close()



class Pizza: 
    def get_cost(self):
        pass
    
    def get_description(self):
        pass


class Margherita(Pizza): 
    def get_cost(self):
        return 10.00
    
    def get_description(self):
        return "Margherita Pizza(Domates sosu,mozzarella peyniri,pesto sos)"
    
class Pepperoni(Pizza):
    def get_cost(self):
        return 12.00
    
    def get_description(self):
        return "Pepperoni Pizza(Domates sosu,mozzarella peyniri,baharatlı sucuk)"
    
class Hawaiian(Pizza):
    def get_cost(self):
        return 15.00
    
    def get_description(self):
        return "Hawaiian Pizza(Mozzarelle peyniri,jambon,ananas,ekstra peynir)1"
    
class Vegetarian(Pizza):
    def get_cost(self):
        return 14.00
    
    def get_description(self):
        return "Vegetarian Pizza(Domates sosu,dere otu,ananas, mısır)"

class Jalapeno(Pizza):
     def get_cost(self):
         return 13.00

     def get_description(self): 
         return "Jalapeno Pizza(Domates sosu,mozzarella peyniri,sucuk,jalapeno biber,mısır)"            




class ToppingDecorator(Pizza):
    def __init__(self, pizza):
        self.pizza = pizza
    
    def get_cost(self):
        return self.pizza.get_cost()
    
    def get_description(self):
        return self.pizza.get_description()


class Ispanak(ToppingDecorator):
    def __init__(self, pizza):
        super().__init__(pizza)
        self.cost = 1.00
        self.description = "Ispanak"
    
    def get_cost(self):
        return self.pizza.get_cost() + self.cost
    
    def get_description(self):
        return self.pizza.get_description() + ", " + self.description
    
class Kori_Sosu(ToppingDecorator):
    def __init__(self, pizza):
        super().__init__(pizza)
        self.cost = 0.25
        self.description = "Köri Sosu"
    
    def get_cost(self):
        return self.pizza.get_cost() + self.cost
    
    def get_description(self):
        return self.pizza.get_description() + ", " + self.description

class Keci_Peyniri(ToppingDecorator):
    def __init__(self, pizza):
        super().__init__(pizza)
        self.cost = 2.00
        self.description = "Keçi Peyniri"
    
    def get_cost(self):
        return self.pizza.get_cost() + self.cost
    
    def get_description(self):
        return self.pizza.get_description() + ", " + self.description     

class Koz_Patlican(ToppingDecorator):
    def __init__(self, pizza):
        super().__init__(pizza)
        self.cost = 1.25
        self.description = "Köz Patlıcan"
    
    def get_cost(self):
        return self.pizza.get_cost() + self.cost
    
    def get_description(self):
        return self.pizza.get_description() + ", " + self.description   

class Misir(ToppingDecorator):
    def __init__(self, pizza):
        super().__init__(pizza)
        self.cost = 0.50
        self.description = "Mısır"
    
    def get_cost(self):
        return self.pizza.get_cost() + self.cost
    
    def get_description(self):
        return self.pizza.get_description() + ", " + self.description           





def main():
    
    file = open('Menu.txt', 'r')
    print(file.read())
    
    while True:

     print("\n\nPizza Seçiniz:\n1:Margherita \n2:Pepperoni \n3:Hawaiian \n4:Vegetarian \n5:Jalapeno \n")
     pizza_choice = int(input())

     pizza = None
     if   pizza_choice == 1:
          pizza = Margherita()
          break
     elif pizza_choice == 2:
          pizza = Pepperoni()
          break
     elif pizza_choice == 3:
          pizza = Hawaiian()
          break
     elif pizza_choice == 4:
          pizza = Vegetarian()   
          break
     elif pizza_choice == 5:     
          pizza = Jalapeno()
          break
     else:
          print("Yanlış Seçim! Tekrar Seçim Yapınız!")
        

    while True:
        print("\nYan Ürün Seçiniz:\n1:Ispanak \n2:Köri Sosu \n3:Keçi Peyniri \n4:Köz Patlıcan \n5:Mısır \n6:Bir Ürün Eklemek İstemiyorum. \n")
        
        topping_choice = int(input())
        if   topping_choice == 1:
             pizza = Ispanak(pizza)
        elif topping_choice == 2:
             pizza = Kori_Sosu(pizza)
        elif topping_choice == 3:
             pizza = Keci_Peyniri(pizza)
        elif topping_choice == 4:
             pizza = Koz_Patlican(pizza)
        elif topping_choice == 5:
             pizza = Misir(pizza)       
        elif topping_choice == 6:
             break
        else:
            print("Yanlış Seçim! Tekrar Seçim Yapınız!")

     
    print("\nPizzanız: ",pizza.get_description())
    print("Toplam Ücret: $", pizza.get_cost())

    print('\nLütfen adınızı girin: ')
    name = input()
    print('Lütfen TC kimlik numaranızı girin: ')
    id_number  = input()
    print('Lütfen kredi kartı numaranızı girin: ')
    card_number = input()
    print('Lütfen kredi kartı sifrenizi girin: ')
    password_number = input()
    
    with open("Orders_Database.csv", 'a') as file_csv:
        writer = csv.writer(file_csv)
        writer.writerow([datetime.datetime.now(), pizza.get_description(), pizza.get_cost(), name, id_number, card_number,password_number])




def information():
    
    info= pd.read_csv("Orders_Database.csv")
    return info

main()

information()

